#!/bin/sh
PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

if [ ! -x /usr/bin/ssh ]; then
	exit 0
fi

. /usr/share/initramfs-tools/hook-functions

if [ ! -d ${DESTDIR}/root/ ]; then
	ROOTDIR="$(cd "${DESTDIR}"; echo root-*)"
else
	ROOTDIR="root"
fi

copy_exec /usr/bin/ssh
mkdir -p ${DESTDIR}/lib/cryptsetup/scripts/
mkdir -p ${DESTDIR}/${ROOTDIR}/.ssh/
cp /lib/cryptsetup/scripts/get_key_ssh ${DESTDIR}/lib/cryptsetup/scripts/get_key_ssh
