#!/bin/sh
PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

if [ ! -x /usr/bin/ssh ]; then
	exit 0
fi

. /usr/share/initramfs-tools/hook-functions

cp /etc/initramfs-tools/root/.ssh/unlock_rsa "${DESTDIR}/root/.ssh/"
cp /etc/initramfs-tools/root/.ssh/unlock_rsa.pub "${DESTDIR}/root/.ssh/"
cp /etc/initramfs-tools/root/.ssh/known_hosts "${DESTDIR}/root/.ssh/"
