#!/bin/sh
PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

if [ ! -x /usr/bin/ssh ]; then
	exit 0
fi

. /usr/share/initramfs-tools/hook-functions

if [ ! -d ${DESTDIR}/root/ ]; then
	ROOTDIR="$(cd "${DESTDIR}"; echo root-*)"
else
	ROOTDIR="root"
fi

cp /etc/initramfs-tools/root/.ssh/unlock_rsa "${DESTDIR}/${ROOTDIR}/.ssh/"
cp /etc/initramfs-tools/root/.ssh/unlock_rsa.pub "${DESTDIR}/${ROOTDIR}/.ssh/"
cp /etc/initramfs-tools/root/.ssh/known_hosts "${DESTDIR}/${ROOTDIR}/.ssh/"
