#!/bin/bash
macAddr=$( echo $SSH_ORIGINAL_COMMAND | tr '[:lower:]' '[:upper:]' )
if [ ! -z "$macAddr" ]; then
	hMacAddr=$( echo $macAddr | sha1sum | cut -c -40 )
	checkHash="PLACEHOLDER_FOR_MAC_ADDRESS"

	if [ "$hMacAddr" == "$checkHash" ]; then
	        cat ~/crypt-keys/PLACEHOLDER_FOR_KEYFILE.keyfile
	else
		echo "nope!"
	fi
fi
